name: Is in PR?
description: Checks if the current commit is part of a PR.
inputs:
  includeDraft:
    description: Boolean to include draft PRs. Defaults to true.
    default: 'true'
  sha:
    description: Commit SHA to check for. Defaults to head SHA.
    default: ${{ github.event.pull_request.head.sha || github.context.sha }}
  github-token:
    description: The GitHub token used to create an authenticated client.
    default: ${{ github.token }}
outputs:
  result:
    description: Boolean indicating if the commit is part of a PR.
runs:
  using: node16
  main: 'dist/index.js'
branding:
  icon: git-pull-request
  color: purple
